# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='company_name',
            field=models.CharField(default='COMPANY', max_length=50),
        ),
        migrations.AlterField(
            model_name='settings',
            name='commission_members',
            field=models.ManyToManyField(max_length=4, to='forms.Commissioner'),
        ),
    ]
