# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20170425_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('seller', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSeries',
            fields=[
                ('series_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.DocumentSeries'),
        ),
        migrations.AddField(
            model_name='settings',
            name='document_series',
            field=models.ManyToManyField(to='forms.DocumentSeries'),
        ),
    ]
