# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissioner',
            name='position',
            field=models.CharField(default='fights teutons', max_length=50),
        ),
    ]
